// Regenerates src/data/live.ts from the gaurdasjimaharaj.in API.
// Usage: npm run sync. Writes nothing if any request fails, so a bad run never wipes the snapshot.
import { writeFileSync } from 'node:fs';

const HOST = 'https://api.gaurdasjimaharaj.in';
const API = `${HOST}/api/v1`;
const OUT = new URL('../src/data/live.ts', import.meta.url);

const get = async (path) => {
  const res = await fetch(`${API}/${path}`, { signal: AbortSignal.timeout(30000) });
  if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`);
  return res.json();
};
const t = (s) => (s ?? '').trim();
// text pasted into the admin editor carries white backgrounds and blank paragraphs; drop them
const html = (s) =>
  t(s)
    .replace(/\s*background-color: rgb\(255, 255, 255\);?/g, '')
    .replace(/ style="\s*"/g, '')
    .replace(/<p><br><\/p>/g, '');
const abs = (p) => (p ? (p.startsWith('http') ? p : HOST + p) : '');
// the API stores pasted <iframe> src fragments: pull out the 11-char video id
const yt = (s) => (s ?? '').match(/(?:embed\/|v=|youtu\.be\/)([\w-]{11})/)?.[1] ?? '';

// run `fn` over `items`, a few at a time, keeping order
async function pool(items, n, fn) {
  const out = [];
  for (let i = 0; i < items.length; i += n) out.push(...(await Promise.all(items.slice(i, i + n).map(fn))));
  return out;
}

const [about, cats, bhajans, gallery, live] = await Promise.all(
  ['about_us', 'category_list', 'bhajans', 'get_gallery_photos', 'live_youtube'].map(get),
);

const CATEGORIES = cats.map((c) => ({ id: c.id, name: t(c.name), description: html(c.description), featured: !!c.is_feature, image: abs(c.image) }));

const rawKathas = (await pool(cats, 6, (c) => get(`kathas_by_category?category_id=${c.id}`))).flat();
const KATHAS = rawKathas
  .map((k) => ({
    id: k.id,
    categoryId: k.category_id,
    name: t(k.name),
    shortDescription: html(k.short_description),
    description: html(k.description),
    dates: t(k.dates),
    status: k.status === 'upcoming' ? 'upcoming' : 'done',
    location: t(k.location),
    time: t(k.time_description),
    images: (k.katha_images ?? []).map(abs),
  }))
  .sort((a, b) => b.id - a.id);

const details = await pool(KATHAS, 8, (k) => get(`about_katha?katha_id=${k.id}`));
const VIDEOS = details
  .flatMap((d) => d.katha_event_videos ?? [])
  .map((v) => ({ id: v.id, kathaId: v.katha_id, name: t(v.name), yt: yt(v.youtube_link) }))
  .filter((v) => v.yt)
  .sort((a, b) => b.id - a.id);

const BHAJANS = bhajans.map((b) => ({ id: b.id, title: t(b.title), yt: yt(b.youtube_link) })).filter((b) => b.yt);

// guard against an API hiccup returning empty lists
if (!CATEGORIES.length || !KATHAS.length) throw new Error('API returned no categories or kathas; keeping the old snapshot');

const j = (v) => JSON.stringify(v, null, 1);
writeFileSync(
  OUT,
  `// Snapshot of the gaurdasjimaharaj.in API (api.gaurdasjimaharaj.in/api/v1), taken ${new Date().toISOString().slice(0, 10)}. Generated by scripts/sync-live.mjs (npm run sync) — edits here are overwritten on the next sync.
export type Category = { id: number; name: string; description: string; featured: boolean; image: string };
export type Katha = { id: number; categoryId: number; name: string; shortDescription: string; description: string; dates: string; status: 'upcoming' | 'done'; location: string; time: string; images: string[] };
export type Video = { id: number; kathaId: number; name: string; yt: string };
export type Bhajan = { id: number; title: string; yt: string };

export const ABOUT: { title: string; html: string } = ${j({ title: t(about.title), html: html(about.description) })};

export const CATEGORIES: Category[] = ${j(CATEGORIES)};

export const KATHAS: Katha[] = ${j(KATHAS)};

export const VIDEOS: Video[] = ${j(VIDEOS)};

export const BHAJANS: Bhajan[] = ${j(BHAJANS)};

export const GALLERY: string[] = ${j((gallery.all_photos ?? []).map(abs))};

export const LIVE_KATHA_YT: string = ${j(yt(live[0]?.name))};
`,
);
console.log(`live.ts: ${CATEGORIES.length} categories, ${KATHAS.length} kathas, ${VIDEOS.length} videos, ${BHAJANS.length} bhajans`);
